### ISSUE TITLE
Problems in use, request help

### ISSUE THREAD

**Issue by zsp1080** [remotesensinginfo/pysl4land#5]
The environment is configured using anaconda, and the relevant library files are installed.

setup Tips：
(pysl4land_36) PS C:\Users\zsp25\Documents\GitHub\pysl4land\pysl4land> python .\setup.py install
C:\Users\zsp25\anaconda3\envs\pysl4land_36\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'include_package_data'
  warnings.warn(msg)
C:\Users\zsp25\anaconda3\envs\pysl4land_36\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
running build_scripts
copying bin\pysl4landicesat2tools.py -> build\scripts-3.6
running install_lib
creating C:\Users\zsp25\anaconda3\envs\pysl4land_36\Lib\site-packages\pysl4land
copying build\lib\pysl4land\pysl4land_gedi.py -> C:\Users\zsp25\anaconda3\envs\pysl4land_36\Lib\site-packages\pysl4land
copying build\lib\pysl4land\pysl4land_icesat2.py -> C:\Users\zsp25\anaconda3\envs\pysl4land_36\Lib\site-packages\pysl4land
copying build\lib\pysl4land\pysl4land_utils.py -> C:\Users\zsp25\anaconda3\envs\pysl4land_36\Lib\site-packages\pysl4land
copying build\lib\pysl4land\__init__.py -> C:\Users\zsp25\anaconda3\envs\pysl4land_36\Lib\site-packages\pysl4land
byte-compiling C:\Users\zsp25\anaconda3\envs\pysl4land_36\Lib\site-packages\pysl4land\pysl4land_gedi.py to pysl4land_gedi.cpython-36.pyc
byte-compiling C:\Users\zsp25\anaconda3\envs\pysl4land_36\Lib\site-packages\pysl4land\pysl4land_icesat2.py to pysl4land_icesat2.cpython-36.pyc
byte-compiling C:\Users\zsp25\anaconda3\envs\pysl4land_36\Lib\site-packages\pysl4land\pysl4land_utils.py to pysl4land_utils.cpython-36.pyc
byte-compiling C:\Users\zsp25\anaconda3\envs\pysl4land_36\Lib\site-packages\pysl4land\__init__.py to __init__.cpython-36.pyc
running install_scripts
copying build\scripts-3.6\pysl4landgeditools.py -> C:\Users\zsp25\anaconda3\envs\pysl4land_36\Scripts
copying build\scripts-3.6\pysl4landicesat2tools.py -> C:\Users\zsp25\anaconda3\envs\pysl4land_36\Scripts
running install_egg_info
Writing C:\Users\zsp25\anaconda3\envs\pysl4land_36\Lib\site-packages\pysl4land-0.1.0-py3.6.egg-info
(pysl4land_36) PS C:\Users\zsp25\Documents\GitHub\pysl4land\pysl4land> pysl4landicesat2tools.py
Traceback (most recent call last):
  File "C:\Users\zsp25\anaconda3\envs\pysl4land_36\Scripts\pysl4landicesat2tools.py", line 37, in <module>
    import pysl4land.pysl4land_icesat2
ImportError: No module named pysl4land.pysl4land_icesat2

**Comment by petebunting** [comment]
Not sure, have you tried restarting your terminal and then reloading the environment? Looks like everything has been copied during the installation so most likely to be related to the Python environment.
